/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/add-feed` | `/add-feed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/failed-jobs` | `/failed-jobs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/feeds` | `/feeds`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/ingestion-logs` | `/ingestion-logs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/raw-data` | `/raw-data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(editor)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/auth` | `/auth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/add-feed` | `/add-feed`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/failed-jobs` | `/failed-jobs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/feeds` | `/feeds`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/ingestion-logs` | `/ingestion-logs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(admin)'}/raw-data` | `/raw-data`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(editor)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}/auth` | `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(user)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/add-feed${`?${string}` | `#${string}` | ''}` | `/add-feed${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/failed-jobs${`?${string}` | `#${string}` | ''}` | `/failed-jobs${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/feeds${`?${string}` | `#${string}` | ''}` | `/feeds${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/ingestion-logs${`?${string}` | `#${string}` | ''}` | `/ingestion-logs${`?${string}` | `#${string}` | ''}` | `${'/(admin)'}/raw-data${`?${string}` | `#${string}` | ''}` | `/raw-data${`?${string}` | `#${string}` | ''}` | `${'/(editor)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(user)'}/auth${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `${'/(user)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/add-feed` | `/add-feed`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/failed-jobs` | `/failed-jobs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/feeds` | `/feeds`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/ingestion-logs` | `/ingestion-logs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(admin)'}/raw-data` | `/raw-data`; params?: Router.UnknownInputParams; } | { pathname: `${'/(editor)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}/auth` | `/auth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(user)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
